import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyShop" model, go to https://sales-tracker-template.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v1",
  storageKey: "DataModel-Shopify-Shop",
  fields: {
    hasSlackAccessToken: {
      type: "computed",
      sourceFile: "api/models/shopifyShop/hasSlackAccessToken.gelly",
      storageKey: "O6l9Pt9AA8LP",
    },
    slackAccessToken: {
      type: "string",
      storageKey:
        "ModelField-RHyoMtsztoZt::FieldStorageEpoch-ErtwdtSHOfuU",
    },
    slackChannelId: {
      type: "string",
      storageKey:
        "ModelField-ftVggZfgpSnl::FieldStorageEpoch-lR3tY4AK4Ik4",
    },
    slackScopes: {
      type: "json",
      default: [],
      storageKey:
        "ModelField-7FCSkiFcikUy::FieldStorageEpoch-vCyePjnasp0L",
    },
  },
  shopify: {
    fields: [
      "address1",
      "address2",
      "checkoutApiSupported",
      "city",
      "cookieConsentLevel",
      "country",
      "countryCode",
      "countryName",
      "countyTaxes",
      "currency",
      "customerAccountsV2",
      "customerEmail",
      "domain",
      "eligibleForCardReaderGiveaway",
      "eligibleForPayments",
      "email",
      "enabledPresentmentCurrencies",
      "finances",
      "forceSsl",
      "gdprRequests",
      "googleAppsDomain",
      "googleAppsLoginEnabled",
      "hasDiscounts",
      "hasGiftCards",
      "hasStorefront",
      "ianaTimezone",
      "latitude",
      "longitude",
      "marketingSmsContentEnabledAtCheckout",
      "moneyFormat",
      "moneyInEmailsFormat",
      "moneyWithCurrencyFormat",
      "moneyWithCurrencyInEmailsFormat",
      "multiLocationEnabled",
      "myshopifyDomain",
      "name",
      "orderTransactions",
      "orders",
      "passwordEnabled",
      "phone",
      "planDisplayName",
      "planName",
      "preLaunchEnabled",
      "primaryLocale",
      "province",
      "provinceCode",
      "refunds",
      "requiresExtraPaymentsAgreement",
      "setupRequired",
      "shopOwner",
      "shopifyCreatedAt",
      "shopifyUpdatedAt",
      "source",
      "syncs",
      "taxShipping",
      "taxesIncluded",
      "timezone",
      "transactionalSmsDisabled",
      "weightUnit",
      "zipCode",
    ],
  },
};
