# Learn more about working with Shopify TOML files with Gadget at https://docs.gadget.dev/guides/plugins/shopify/advanced-topics/shopify-app-toml

client_id = "e24bf61de4bfd1939d3f37d2d15757c2"
name = "product-quiz-public-rrv7-d"
application_url = "https://product-quiz-public-rrv7-d--development.gadget.app/api/shopify/install-or-render"
embedded = true

[build]
# Gadget manages all your scopes, webhooks and api versioning for your app
# As such, this line should not be changed unless you are working with
# Shopify managed installations. Read more at https://docs.gadget.dev/guides/plugins/shopify/advanced-topics/shopify-app-toml
include_config_on_deploy = false

[auth]
redirect_urls = ["https://product-quiz-public-rrv7-d--development.gadget.app/api/connections/auth/shopify/callback"]

[webhooks]
api_version = "2025-01"
