import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyShop" model, go to https://product-bundler-public-rrv7-d.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v1",
  storageKey: "DataModel-Shopify-Shop",
  fields: {
    bundleComponentQuantitiesDefinitionId: {
      type: "string",
      storageKey: "4ke4q2jGSVtx",
    },
    bundleComponents: {
      type: "hasMany",
      children: { model: "bundleComponent", belongsToField: "shop" },
      storageKey: "4ggtiGREF84t",
    },
    bundleCount: {
      type: "computed",
      sourceFile: "api/models/shopifyShop/bundleCount.gelly",
      storageKey: "Dxuc3F6vYgBk",
    },
    bundles: {
      type: "hasMany",
      children: { model: "bundle", belongsToField: "shop" },
      storageKey: "TO6G5NJTrTYC",
    },
    componentReferenceDefinitionId: {
      type: "string",
      storageKey: "AHjRheeieJEu",
    },
    isBundleDefinitionId: {
      type: "string",
      storageKey: "fchFA_4aPsSw",
    },
    onlineStorePublicationId: {
      type: "string",
      storageKey: "I_Pbew2oxHqD",
    },
  },
  shopify: {
    fields: [
      "address1",
      "address2",
      "alerts",
      "billingAddress",
      "checkoutApiSupported",
      "city",
      "countriesInShippingZones",
      "country",
      "countryCode",
      "countryName",
      "countyTaxes",
      "currency",
      "currencyFormats",
      "customerAccounts",
      "customerAccountsV2",
      "customerEmail",
      "description",
      "domain",
      "eligibleForPayments",
      "email",
      "enabledPresentmentCurrencies",
      "files",
      "finances",
      "gdprRequests",
      "googleAppsDomain",
      "googleAppsLoginEnabled",
      "hasDiscounts",
      "hasGiftCards",
      "hasStorefront",
      "ianaTimezone",
      "latitude",
      "longitude",
      "marketingSmsContentEnabledAtCheckout",
      "moneyFormat",
      "moneyInEmailsFormat",
      "moneyWithCurrencyFormat",
      "moneyWithCurrencyInEmailsFormat",
      "multiLocationEnabled",
      "myshopifyDomain",
      "name",
      "orderNumberFormatPrefix",
      "orderNumberFormatSuffix",
      "passwordEnabled",
      "phone",
      "plan",
      "planDisplayName",
      "planName",
      "preLaunchEnabled",
      "primaryLocale",
      "productMedia",
      "productVariants",
      "products",
      "province",
      "provinceCode",
      "requiresExtraPaymentsAgreement",
      "resourceLimits",
      "richTextEdiorUrl",
      "setupRequired",
      "shipsToCountries",
      "shopOwner",
      "shopifyCreatedAt",
      "shopifyUpdatedAt",
      "source",
      "syncs",
      "taxShipping",
      "taxesIncluded",
      "taxesOffset",
      "timezone",
      "timezoneAbbreviation",
      "timezoneOffsetMinutes",
      "transactionalSmsDisabled",
      "unitSystem",
      "url",
      "weightUnit",
      "zipCode",
    ],
  },
};
