api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "bundle"
type = "function"
uid = "59875f0f-03d5-fbab-2ec0-08c2c45c43b3b3ae184e"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
