import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyShop" model, go to https://wishlist-template.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v1",
  storageKey: "DataModel-Shopify-Shop",
  fields: {
    defaultUpdateFrequency: {
      type: "enum",
      default: "monthly",
      acceptMultipleSelections: false,
      acceptUnlistedOptions: false,
      options: ["weekly", "monthly", "quarterly"],
      validations: { required: true },
      storageKey: "QH2PpsD46lTz",
    },
    wishlistItems: {
      type: "hasMany",
      children: { model: "wishlistItem", belongsToField: "shop" },
      storageKey: "nV1897_LCqr1",
    },
    wishlistMetafieldDefinitionId: {
      type: "string",
      storageKey: "V40YpVDvRHvK",
    },
    wishlists: {
      type: "hasMany",
      children: { model: "wishlist", belongsToField: "shop" },
      storageKey: "0lDf53ksO0N2",
    },
  },
  shopify: {
    fields: [
      "address1",
      "address2",
      "checkoutApiSupported",
      "city",
      "cookieConsentLevel",
      "country",
      "countryCode",
      "countryName",
      "countyTaxes",
      "currency",
      "customerAccountsV2",
      "customerEmail",
      "customers",
      "domain",
      "eligibleForCardReaderGiveaway",
      "eligibleForPayments",
      "email",
      "enabledPresentmentCurrencies",
      "finances",
      "forceSsl",
      "gdprRequests",
      "googleAppsDomain",
      "googleAppsLoginEnabled",
      "hasDiscounts",
      "hasGiftCards",
      "hasStorefront",
      "ianaTimezone",
      "latitude",
      "longitude",
      "marketingSmsContentEnabledAtCheckout",
      "moneyFormat",
      "moneyInEmailsFormat",
      "moneyWithCurrencyFormat",
      "moneyWithCurrencyInEmailsFormat",
      "multiLocationEnabled",
      "myshopifyDomain",
      "name",
      "passwordEnabled",
      "phone",
      "planDisplayName",
      "planName",
      "preLaunchEnabled",
      "primaryLocale",
      "productImages",
      "productVariants",
      "products",
      "province",
      "provinceCode",
      "requiresExtraPaymentsAgreement",
      "setupRequired",
      "shopOwner",
      "shopifyCreatedAt",
      "shopifyUpdatedAt",
      "source",
      "syncs",
      "taxShipping",
      "taxesIncluded",
      "timezone",
      "transactionalSmsDisabled",
      "weightUnit",
      "zipCode",
    ],
  },
};
