# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7fa72d01a6c6f0b2b4d81d0e07fb5bb6"
name = "product-quiz-public-remix-ssr"
application_url = "https://product-quiz-public-remix-ssr--devaoc.gadget.app/api/shopify/install-or-render"
embedded = true

[build]
dev_store_url = "devaoc-test-store.myshopify.com"
include_config_on_deploy = false

[auth]
redirect_urls = [
  "https://product-quiz-public-remix-ssr--devaoc.gadget.app/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2025-01"
