import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyShop" model, go to https://slack-notification-template.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v1",
  storageKey: "DataModel-Shopify-Shop",
  fields: {
    hasSlackAccessToken: {
      type: "boolean",
      default: false,
      validations: { required: true },
      storageKey:
        "ModelField-qpLdc-wxkphq::FieldStorageEpoch-8GYQlz6vL8hK",
    },
    slackAccessToken: {
      type: "string",
      storageKey:
        "ModelField-f-0HVA8chgNo::FieldStorageEpoch-tSyWOnwA-lBo",
    },
    slackChannelId: {
      type: "string",
      default: "",
      storageKey:
        "ModelField-0N3D_jeHckhg::FieldStorageEpoch-9HAAVJLzhSZ2",
    },
    slackScopes: {
      type: "json",
      default: [],
      storageKey:
        "ModelField-cd1aa94YfuOw::FieldStorageEpoch-P9zhHYt0IgaR",
    },
  },
  shopify: {
    fields: [
      "address1",
      "address2",
      "checkoutApiSupported",
      "city",
      "cookieConsentLevel",
      "country",
      "countryCode",
      "countryName",
      "countyTaxes",
      "currency",
      "customerAccountsV2",
      "customerEmail",
      "customers",
      "domain",
      "eligibleForCardReaderGiveaway",
      "eligibleForPayments",
      "email",
      "enabledPresentmentCurrencies",
      "finances",
      "forceSsl",
      "gdprRequests",
      "googleAppsDomain",
      "googleAppsLoginEnabled",
      "hasDiscounts",
      "hasGiftCards",
      "hasStorefront",
      "ianaTimezone",
      "latitude",
      "longitude",
      "marketingSmsContentEnabledAtCheckout",
      "moneyFormat",
      "moneyInEmailsFormat",
      "moneyWithCurrencyFormat",
      "moneyWithCurrencyInEmailsFormat",
      "multiLocationEnabled",
      "myshopifyDomain",
      "name",
      "orderTransactions",
      "orders",
      "passwordEnabled",
      "phone",
      "planDisplayName",
      "planName",
      "preLaunchEnabled",
      "primaryLocale",
      "province",
      "provinceCode",
      "requiresExtraPaymentsAgreement",
      "setupRequired",
      "shopOwner",
      "shopifyCreatedAt",
      "shopifyUpdatedAt",
      "source",
      "syncs",
      "taxShipping",
      "taxesIncluded",
      "timezone",
      "transactionalSmsDisabled",
      "weightUnit",
      "zipCode",
    ],
  },
};
