# Learn more about working with Shopify TOML files with Gadget at https://docs.gadget.dev/guides/plugins/shopify/advanced-topics/shopify-app-toml

client_id = "610bf8a9b9497714a9cc10bfd90befae"
name = "product-tagger-public-template"
application_url = "https://product-tagger-public-template.gadget.app/api/shopify/install-or-render"
embedded = true

[auth]
redirect_urls = [ "https://product-tagger-public-template.gadget.app/api/connections/auth/shopify/callback" ]

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
uri = "https://webhooks.gadget-services.net/shopify/v1?domain=product-tagger-public-template.gadget.app"
topics = [ "products/create", "products/delete", "shop/update", "app/uninstalled" ]

[[webhooks.subscriptions]]
uri = "https://webhooks.gadget-services.net/shopify/v1/shopifyProduct-update?domain=product-tagger-public-template.gadget.app"
topics = [ "products/update" ]
include_fields = [ "id", " body" ]
[access_scopes]
scopes = "write_products, read_products"
