# Learn more about working with Shopify TOML files with Gadget at https://docs.gadget.dev/guides/plugins/shopify/advanced-topics/shopify-app-toml

client_id = "ccd7d9fbe64ab29c2f6adfcb42bbc3ee"
name = "product-bundles-public"
application_url = "https://product-bundles-public-template.gadget.app/api/shopify/install-or-render"
embedded = true

[auth]
redirect_urls = [ "https://product-bundles-public-template.gadget.app/api/connections/auth/shopify/callback" ]

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
uri = "https://webhooks.gadget-services.net/shopify/v1?domain=product-bundles-public-template.gadget.app"
topics = [ "products/create", "products/update", "products/delete", "shop/update", "app/uninstalled" ]

[access_scopes]
scopes = "write_products, read_products, write_publications, read_publications, write_cart_transforms, read_cart_transforms"
