name: Blog template Deployment

on:
  push:
    paths:
      - "web/blog-template/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  push-to-development-environment:
    runs-on: macos-latest
    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v4
      - name: Push to development environment
        run: npx ggt push --app=blog-template --env=development --force --allow-unknown-directory
        working-directory: web/blog-template/
        env:
          GGT_TOKEN: ${{ secrets.BLOG_DEPLOY_TOKEN }}
