name: Customized Bundle Deployment

on:
  push:
    paths:
      - "bundle-template/**"
    branches:
      - main

jobs:
  push-to-development-environment:
    runs-on: macos-latest
    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v4
      - name: Push to development environment
        run: npx ggt push --app=bundle-template --env=development --force --allow-unknown-directory
        working-directory: bundle-template/
        env:
          GGT_TOKEN: ${{ secrets.BUNDLE_DEPLOY_TOKEN }}
