name: Carrier Service Deployment

on:
  push:
    paths:
      - "shopify/carrier-service-template/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  push-to-development-environment:
    runs-on: macos-latest
    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v4
      - name: Push to development environment
        run: npx ggt push --app=carrier-service-template --env=development --force --allow-unknown-directory
        working-directory: shopify/carrier-service-template/
        env:
          GGT_TOKEN: ${{ secrets.CARRIER_SERVICE_DEPLOY_TOKEN }}
