name: CI/CD Pipeline

on:
  push:
    paths:
      - "chatgpt-template/**"
    branches:
      - main

jobs:
  push-to-development-environment:
    runs-on: macos-latest
    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v4
      - name: Push to development environment
        run: npx ggt push --app=chatgpt-template --env=development --force --allow-unknown-directory
        working-directory: chatgpt-template/
        env:
          GGT_TOKEN: ${{ secrets.CHATGPT_DEPLOY_TOKEN }}
