name: CI/CD Pipeline

on:
  push:
    paths:
      - "customized-customized-bundle-template/**"
    branches:
      - main

jobs:
  push-to-development-environment:
    runs-on: macos-latest
    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v4
      - name: Push to development environment
        run: npx ggt push --app=customized-bundle-template --env=development --force --allow-unknown-directory
        working-directory: customized-bundle-template/
        env:
          GGT_TOKEN: ${{ secrets.BUNDLE_DEPLOY_TOKEN }}
