name: Customized Bundle Deployment

on:
  push:
    paths:
      - "shopify/customized-bundle-template/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  push-to-development-environment:
    runs-on: macos-latest
    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v4
      - name: Push to development environment
        run: npx ggt push --app=customized-bundle-template --env=development --force --allow-unknown-directory
        working-directory: shopify/customized-bundle-template/
        env:
          GGT_TOKEN: ${{ secrets.CUSTOMIZED_BUNDLE_DEPLOY_TOKEN }}
