name: External Shopify Template Deployment

on:
  push:
    paths:
      - "external-shopify-template/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  push-to-development-environment:
    runs-on: macos-latest
    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v4
      - name: Push to development environment
        run: npx ggt push --app=external-shopify-template --env=development --force --allow-unknown-directory
        working-directory: external-shopify-template/
        env:
          GGT_TOKEN: ${{ secrets.CHATGPT_DEPLOY_TOKEN }}
