name: CI/CD Pipeline

on:
  push:
    paths:
      - "monthy-subscription-template/**"
    branches:
      - main

jobs:
  push-to-development-environment:
    runs-on: macos-latest
    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v4
      - name: cd to correct folder
        run: cd monthy-subscription-template/
      - name: Push changes to development environment
        run: npx ggt push --app=monthy-subscription-template --env=development --force --allow-unknown-directory
        with:
          env:
            GGT_TOKEN: ${{ secrets.MONTHLY_SUBSCRIPTION_DEPLOY_TOKEN }}
