name: Monthly Subscription Deployment

on:
  push:
    paths:
      - "monthy-subscription-template/**"
    branches:
      - main
  workflow_dispatch:
    paths:
      - "monthy-subscription-template/**"

jobs:
  push-to-development-environment:
    runs-on: macos-latest
    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v4
      - name: Push to development environment
        run: npx ggt push --app=monthy-subscription-template --env=development --force --allow-unknown-directory
        working-directory: monthy-subscription-template/
        env:
          GGT_TOKEN: ${{ secrets.MONTHLY_SUBSCRIPTION_DEPLOY_TOKEN }}
