name: CI/CD Pipeline

on:
  push:
    paths:
      - "one-time-charge-template/**"
    branches:
      - main

jobs:
  push-to-development-environment:
    runs-on: macos-latest
    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v4
      - name: cd to correct folder
        run: cd one-time-charge-template/
      - name: Push changes to development environment
        run: npx ggt push --app=one-time-charge-template --env=development --force --allow-unknown-directory
        with:
          env:
            GGT_TOKEN: ${{ secrets.ONE_TIME_CHARGE_DEPLOY_TOKEN }}
