name: CI/CD Pipeline

on:
  push:
    paths:
      - "pre-purchase-template/**"
    branches:
      - main

jobs:
  push-to-development-environment:
    runs-on: macos-latest
    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v4
      - name: Push to development environment
        run: npx ggt push --app=pre-purchase-template --env=development --force --allow-unknown-directory
        working-directory: pre-purchase-template/
        env:
          GGT_TOKEN: ${{ secrets.PRE_PURCHASE_DEPLOY_TOKEN }}
