name: Product Tagger Deployment

on:
  push:
    paths:
      - "shopify/product-tagger-template/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  push-to-development-environment:
    runs-on: macos-latest
    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v4
      - name: Push to development environment
        run: npx ggt push --app=product-tagger-template --env=development --force --allow-unknown-directory
        working-directory: shopify/product-tagger-template/
        env:
          GGT_TOKEN: ${{ secrets.PRODUCT_TAGGER_DEPLOY_TOKEN }}
