name: Product Reviews Deployment

on:
  push:
    paths:
      - "product-reviews-template/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  push-to-development-environment:
    runs-on: macos-latest
    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v4
      - name: Push to development environment
        run: npx ggt push --app=product-reviews-template --env=development --force --allow-unknown-directory
        working-directory: product-reviews-template/
        env:
          GGT_TOKEN: ${{ secrets.PRODUCT_REVIEWS_DEPLOY_TOKEN }}
