name: pt-custom-remix-spa

on:
  push:
    paths:
      - "shopify/product-tagger/product-tagger-custom-remix-spa/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  push-to-development-environment:
    runs-on: macos-latest
    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v4
      - name: Push to development environment
        run: npx ggt push --app=product-tagger-custom-remix-spa --env=development --force --allow-unknown-directory
        working-directory: shopify/product-tagger/product-tagger-custom-remix-spa/
        env:
          GGT_TOKEN: ${{ secrets.PRODUCT_TAGGER_CUSTOM_REMIX_SPA_DEPLOY_TOKEN }}
