name: Product Quiz Deployment

on:
  push:
    paths:
      - "product-quiz-template/**"
    branches:
      - main

jobs:
  push-to-development-environment:
    runs-on: macos-latest
    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v4
      - name: Push to development environment
        run: npx ggt push --app=product-quiz-template --env=development --force --allow-unknown-directory
        working-directory: product-quiz-template/
        env:
          GGT_TOKEN: ${{ secrets.PRODUCT_QUIZ_DEPLOY_TOKEN }}
