name: s-noauth-rrv7-f-ssr

on:
  push:
    paths:
      - "web/screenwriter/screenwriter-noauth-rrv7-f-ssr/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  push-to-development-environment:
    runs-on: macos-latest
    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v4
      - name: Push to development environment
        run: npx ggt push --app=screenwriter-noauth-rrv7-f-ssr --env=development --force --allow-unknown-directory
        working-directory: web/screenwriter/screenwriter-noauth-rrv7-f-ssr/
        env:
          GGT_TOKEN: ${{ secrets.SCREENWRITER_NOAUTH_RRV7_F_SSR_DEPLOY_TOKEN }}
