name: Shopify-Instagram Deployment

on:
  push:
    paths:
      - "shopify-instagram-template/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  push-to-development-environment:
    runs-on: macos-latest
    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v4
      - name: Push to development environment
        run: npx ggt push --app=shopify-instagram-template --env=development --force --allow-unknown-directory
        working-directory: shopify-instagram-template/
        env:
          GGT_TOKEN: ${{ secrets.SHOPIFY_INSTAGRAM_DEPLOY_TOKEN }}
