name: Slack Notification Deployment

on:
  push:
    paths:
      - "slack-notification-template/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  push-to-development-environment:
    runs-on: macos-latest
    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v4
      - name: Push to development environment
        run: npx ggt push --app=slack-notification-template --env=development --force --allow-unknown-directory
        working-directory: slack-notification-template/
        env:
          GGT_TOKEN: ${{ secrets.SLACK_NOTIFICATION_DEPLOY_TOKEN }}
