name: Stripe Deployment

on:
  push:
    paths:
      - "web/stripe-template/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  push-to-development-environment:
    runs-on: macos-latest
    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v4
      - name: Push to development environment
        run: npx ggt push --app=stripe-template --env=development --force --allow-unknown-directory
        working-directory: web/stripe-template/
        env:
          GGT_TOKEN: ${{ secrets.STRIPE_DEPLOY_TOKEN }}
