name: Tailwind CSS Deployment

on:
  push:
    paths:
      - "tailwind-css-template/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  push-to-development-environment:
    runs-on: macos-latest
    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v4
      - name: Push to development environment
        run: npx ggt push --app=tailwind-css-template --env=development --force --allow-unknown-directory
        working-directory: tailwind-css-template/
        env:
          GGT_TOKEN: ${{ secrets.TAILWIND_CSS_DEPLOY_TOKEN }}
